# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Stroppy
description: framework for testing various databases. It allows you to deploy a cluster in the cloud, run load tests and simulate various problems, for example,network unavailability of one of the nodes in the cluster.
#baseurl: "/stroppy"
url: "https://stroppy.io" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: just-the-docs
color_scheme: light

aux_links:
  "GitHub":
    - "//github.com/picodata/stroppy"

logo: "/assets/images/stroppy.png"

plugins:
  - jekyll-lunr-js-search-multilingual
  - jekyll-multiple-languages-plugin

languages: ["en", "ru"]

exclude_from_localizations: ["javascript", "images", "css"]

#default_locale_in_subfolder: true

#search options
# Enable or disable the site search
# Supports true (default) or false
search_enabled: true

search:
  # Split pages into sections that can be searched individually
  # Supports 1 - 6, default: 2
  heading_level: 2
  # Maximum amount of previews per search result
  # Default: 3
  previews: 3
  # Maximum amount of words to display before a matched word in the preview
  # Default: 5
  preview_words_before: 5
  # Maximum amount of words to display after a matched word in the preview
  # Default: 10
  preview_words_after: 10
  # Set the search token separator
  # Default: /[\s\-/]+/
  # Example: enable support for hyphenated search words
  tokenizer_separator: /[\s/]+/
  # Display the relative url in search results
  # Supports true (default) or false
  rel_url: true
  # Enable or disable the search button that appears in the bottom right corner of every page
  # Supports true or false (default)
  button: false
# Enable or disable heading anchors
heading_anchors: true

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

nav_sort: case_insensitive

# Footer content
# appears at the bottom of every page's main content
# Note: The footer_content option is deprecated and will be removed in a future major release. Please use `_includes/footer_custom.html` for more robust markup / liquid-based content.
footer_content: "Copyright &copy; 2021 picodata.io. Distributed by an <a href=\"https://github.com/picodata/stroppy/blob/develop/LICENSE\">BSD 2-Clause License.</a>"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
